### PR TITLE
Allow users to change keybindings for cameras

### PR DESCRIPTION
**Pull request by Aztro-dev**
This pull request allows the people who use this crate to change their camera's keybindings to whatever they wish.

### CODE REVIEW

**Comment by bonsairobo** [comment]
@Aztro-dev have you looked at this?

https://github.com/bonsairobo/smooth-bevy-cameras/issues/5

**Comment by DaAwesomeP** [comment]
This would be very helpful--I currently have some GUI windows that pop up and the scroll wheel activates both the GUI and camera simultaneously; this would allow me to remap zoom to CTRL + scroll.

**Comment by bonsairobo** [comment]
@Aztro-dev @DaAwesomeP

Please read my response in #5. The ability to provide custom bindings already exists. Just use `override_input_system` on the controller plugin you want to use, and provide your own system that generates `ControlEvent`s.

**Comment by DaAwesomeP** [comment]
@bonsairobo OK, I resolved it by copying in and overriding the entire `default_input_map` in my app. Feels a little bit clunky since I am changing basically one line of it, but it works.

**Pull request closed without merging**
